# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a378bfdf90195ec1a4f363d1482a31b00eaa33cf2b98210ed8662d04379fff543f52840f86b04cf2da9d464cb4a5b384a62601e375d75f40c7b3694f6fa57719

test:
  secret_key_base: a5e8e90e011572bb235da311b1cb6a8e8ec9832cf609da4e8bb701b654f1b7cab098a9049bbc667cd99b9fa901e2238a727d5aabb7c2fb76f718a83745b93037

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
